fix: get fields with comma
wandera/1password-client pull request #60
Opened 2024-05-24 19:22 UTC by fzipi360

Fixes #59

2024-05-27 15:08 UTC, dtpryce commented
I need to dig into this one a little bit but will try to test out this week

2024-05-28 11:21 UTC, dtpryce requested changes

2024-05-28 11:21 UTC, dtpryce commented on onepassword/client.py
> +                label = i["label"]
Ran a test using a login item that had a password with a comma in it. Performed:
```
from onepassword import OnePassword

op = OnePassword()
uuid = op.get_uuid("test login")
password = op.get_item(uuid, fields=["password"])

```
And got following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "REDACTED/1password-client/onepassword/client.py", line 440, in get_item
    label = i["label"]
TypeError: string indices must be integers
```
And from quick scan you need to make sure you are using python 3.10 or higher here. Dictionaries are iterated using this syntax:

```
for k, v in dictionary.items():
   print(k, v)
```

Hope that helps with your next commit :D

2024-05-28 12:19 UTC, fzipi360 commented on onepassword/client.py
> +                label = i["label"]
Ah, good catch! Will update to support older versions.

2024-05-28 13:08 UTC, fzipi360 commented on onepassword/client.py
> +                label = i["label"]
Used `.items()` in f3ee92a6652a80f9ad780d859c2d03e754618d90. Do you think we can mock a test for this, or do we need to use manual testing?

2024-05-28 14:50 UTC, closed without merging