feat: add support for otp fields
wandera/1password-client pull request #61
Opened 2024-05-27 14:48 UTC by fzipi360

## what

- add support for otp fields

## why

- there is no support for otp as it requires a specific flag to be passed to 1pass cli

2024-05-27 15:06 UTC, dtpryce requested changes
I am guessing this is always just a single line string so should be more than fine, but can you add a test for this new method? Just a very basic on mocking the other get methods please!

2024-05-27 19:09 UTC, fzipi360 commented
🤔 from what I see [here](https://github.com/wandera/1password-client/blob/main/test/test_client.py), there is not much room for mocking there... unless creating everything from scratch.

2024-05-28 09:59 UTC, dtpryce commented
> 🤔 from what I see [here](https://github.com/wandera/1password-client/blob/main/test/test_client.py), there is not much room for mocking there... unless creating everything from scratch.

yeah it's nothing special since we are just wrapping the cli happy for it be:

```
def test_get_item_otp(self):
        """
        Tested in read_bash_return.
        """
        pass
```

Just for completeness

2024-05-28 11:22 UTC, dtpryce commented
> > 🤔 from what I see [here](https://github.com/wandera/1password-client/blob/main/test/test_client.py), there is not much room for mocking there... unless creating everything from scratch.
> 
> yeah it's nothing special since we are just wrapping the cli happy for it be:
> 
> ```
> def test_get_item_otp(self):
>         """
>         Tested in read_bash_return.
>         """
>         pass
> ```
> 
> Just for completeness

ok I will test that this works but no reason why it wouldn't and add the test for you so you can focus on the comma within fields PR.

2024-05-28 12:04 UTC, dtpryce commented
Merged in #62 ... will release soon

2024-05-28 12:04 UTC, closed without merging