add --reveal to cli for v2.30.0 and later
wandera/1password-client pull request #65
Opened 2024-09-06 16:26 UTC by csteinle

- adds `--reveal` when getting items if CLI is version v2.30.0 or later
- resolves #64

2024-09-16 09:21 UTC, dtpryce requested changes
As mentioned in a comment I would actually go with making 2.30.0 the minimum supported version which would also need:

* README updated to reflect this
* https://github.com/wandera/1password-client/blob/233184937d93719233759edd350f3516da859fd7/install_op.py#L8 updated to reflect this
* testing to make sure all methods work with new client (follow basic steps in README is enough for me)

Happy to discuss, thanks for the great contribution. Pretty much there!

2024-09-16 09:21 UTC, dtpryce commented on onepassword/client.py
> +    cli_version = tuple(map(int, read_bash_return("op --version").split(".")))
We actually try not to do this and just fix the version in the `install.py` it gave us a lot more headaches trying to be fully backwards compatible and so we try to maintain and bump when we can. I know we suggest you can have any version over 2.0.0 in the README but if this new flag is a break change, let's update that suggestion :D

2024-09-16 09:21 UTC, dtpryce commented on onepassword/client.py
> +        reveal = "--reveal" if cls.cli_version >= (2, 30, 0) else ""
If we go with my suggestions you won't need this and can just add `--reveal` to every `op` call that requires it

2026-07-02 09:52 UTC, csteinle commented
I won't have time to revist this, so closing.

2026-07-02 09:52 UTC, closed without merging