feat: add support for read CLI command
wandera/1password-client pull request #69
Opened 2024-11-03 01:50 UTC by rokn

inspired by [adnandaut](https://github.com/adnandaut) and my needs.

fixes #66 by adding support for the read CLI command

this can be tested like this:
```
>>> from onepassword import OnePassword
>>> OnePassword.read("<a secret reference>")
```

2024-11-03 17:57 UTC, dtpryce commented
Nice PR! Any chance you can also add support for getting the secret reference in a new class method? Then everything in the user workflow can be done in python too?

2024-11-03 17:57 UTC, dtpryce commented
Also is this only support by a certain cli version?

2024-11-03 20:34 UTC, rokn commented
> Nice PR! Any chance you can also add support for getting the secret reference in a new class method? Then everything in the user workflow can be done in python too?

Thanks! I'm not sure if that's something users would want to do as I imagine that this will be used to fill in secrets which are already set from somewhere. But even so there is a way to get the reference with the current API:
```
OnePassword.get_item("Item")["fields"][0]['reference']
```

> Also is this only support by a certain cli version?

The read command is available for 2.0 and up (ref: https://app-updates.agilebits.com/product_history/CLI2#2.0.0:~:text=Secfault%20Security.%20%7B2183%7D-,2.0.0,-(build%20%232000019)%20%E2%80%93%20released)

2024-11-04 12:52 UTC, dtpryce commented
> > Nice PR! Any chance you can also add support for getting the secret reference in a new class method? Then everything in the user workflow can be done in python too?
> 
> Thanks! I'm not sure if that's something users would want to do as I imagine that this will be used to fill in secrets which are already set from somewhere. But even so there is a way to get the reference with the current API:
> 
> ```
> OnePassword.get_item("Item")["fields"][0]['reference']
> ```
> 
> > Also is this only support by a certain cli version?
> 
> The read command is available for 2.0 and up (ref: https://app-updates.agilebits.com/product_history/CLI2#2.0.0:~:text=Secfault%20Security.%20%7B2183%7D-,2.0.0,-(build%20%232000019)%20%E2%80%93%20released)

Ok great! So I would also suggest some clear example(s) in the README then to make sure users know how to use! Since it's v2+ then we are good, I do intend to update with a fixed version we support since we keep getting issues with backwards compatibility and users installing the cli as they wish.

2024-11-04 12:53 UTC, dtpryce requested changes
As mentioned in comments - please add some example(s) in README

2024-11-04 12:54 UTC, dtpryce commented
Would this also resolve the need for `--reveal` seen in #65 ?

2024-11-04 13:11 UTC, rokn commented
Added the README updates.

I'm not sure this has anything to do with the `--reveal` requirement.

2024-11-04 16:37 UTC, LPLabrys99 commented
This PR adds a capability which I couldn't find elsewhere in this module - reading file attachments from regular secrets. It seems the only way to do it currently is with the CLI command `op read ...`

2025-01-06 12:01 UTC, dtpryce approved these changes

2025-01-06 12:01 UTC, merged